### ISSUE TITLE
CI failure / CI 挂了

### ISSUE THREAD

**Issue by Fatman13** [ipfs-force-community/sophon-docs#10]
昨天手动 pr 的一个还好的，不知道为啥今天突然挂了。。。😂 CC @LinZexiao 也看看？

**Comment by Fatman13** [comment]
图片的问题？我在想是不是我们图片都可以直接贴在 github 上，用 github 的链接。这样原来文档如果有图片的话，链接过来，应该也不会挂？

例：下图的链接 https://github.com/ipfs-force-community/sophon-docs/assets/1591330/a6c72185-09f4-4176-88b7-e279bc99f491

![image](https://github.com/ipfs-force-community/sophon-docs/assets/1591330/a6c72185-09f4-4176-88b7-e279bc99f491)

**Comment by LinZexiao** [comment]
确实是 图片的问题, 文档使用了相对路径,所以,一旦文档迁移了,图片就不可用了, 让文档引用 图床的地址或者 github 的地址能解决这个问题, 就是不知道,github 图片的连接能保存多久

**Comment by Fatman13** [comment]
![image](https://github.com/ipfs-force-community/sophon-docs/assets/1591330/c4de6a0b-2c33-4fee-8eff-0bc92614c42b)

**Comment by Fatman13** [comment]
![image](https://github.com/ipfs-force-community/sophon-docs/assets/1591330/150df3c1-eda5-49ae-8d05-4bfb68254281)

**Comment by Fatman13** [comment]
![image](https://github.com/ipfs-force-community/sophon-docs/assets/1591330/aeed760e-6b54-4400-8aa8-7a5878469c7c)

**Comment by Fatman13** [comment]
![image](https://github.com/ipfs-force-community/sophon-docs/assets/1591330/883c12f1-fbd0-4d94-b123-6c5fb312dd0a)
